apiVersion: v1
kind: Service
metadata:
  name: flask-ecom-svc
  namespace: NAMESPACE
  labels:
    app: flask-ecom
    environment: ENV_NAME
spec:
  selector:
    app: flask-ecom
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: NODE_PORT
  type: NodePort
